config/routes.rb
Mazer::Application.routes.draw do |map|

  resources :mazes do
    resources :nodes do
      resources :links
    end 
  end

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login 
  
  root :to => 'mazes#index'

  resources :sessions

  resources :users

end

app/models/link.rb
class Link < ActiveRecord::Base 
  
  belongs_to  :node
  
  attr_accessible :text, :node_id, :to_node_id
end

app/models/maze.rb
class Maze < ActiveRecord::Base
  
  belongs_to  :maze 
  has_many    :nodes
  
  attr_accessible :title, :user_id
end

app/models/node.rb
class Node < ActiveRecord::Base 
  
  belongs_to  :maze
  has_many    :links
  
  attr_accessible :title, :content, :maze_id
end

app/models/user.rb
class User < ActiveRecord::Base 
  
  has_many  :mazes
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :prepare_password
  
  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true
  
  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end
  
  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end
  
  private
  
  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hash = encrypt_password(password)
    end
  end
  
  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  protect_from_forgery
  layout 'application'
  
  protected
  
  def get_maze
    @maze = current_user.mazes.find params[:maze_id]    
  end
  
  def get_node
    @node = @maze.nodes.find params[:node_id]
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :login_required
  before_filter :get_maze
  before_filter :get_node
  
  def new
    @link = @node.links.new
    @nodes = @maze.nodes.all.collect { |n| [n.title, n.id] }
  end
  
  def create
    @link = @node.links.new(params[:link])
    if @link.save
      flash[:notice] = "Successfully created link."
      redirect_to edit_maze_node_path(@maze, @node)
    else 
      flash[:error] = "Link wasn't created"
      redirect_to new_maze_node_link_path(@maze, @node)
    end
  end
  
  def edit
    @link = @node.links.find(params[:id])
    @nodes = @maze.nodes.all.collect { |n| [n.title, n.id] }
  end
  
  def update
    @link = @node.links.find(params[:id])
    if @link.update_attributes(params[:link])
      flash[:notice] = "Successfully updated link."
    redirect_to edit_maze_node_path(@maze, @node)
    else
      flash[:error] = "Link wasn't updated"
      redirect_to edit_maze_node_link_path(@maze, @node)
    end
  end
  
  def destroy
    @link = @node.links.find(params[:id])
    @link.destroy
    flash[:notice] = "Successfully destroyed link."
    redirect_to maze_node_path @maze, @node
  end
end

app/controllers/mazes_controller.rb
class MazesController < ApplicationController
  
  before_filter :login_required
  
  def index 
    @mazes = current_user.mazes.all
  end
  
  def show
    @maze = current_user.mazes.find(params[:id])
    @node = @maze.nodes.first
    redirect_to maze_node_url(@maze, @node)
  end
  
  def new
    @maze = current_user.mazes.new
  end
  
  def create
    @maze = current_user.mazes.new(params[:maze])
    if @maze.save
      flash[:notice] = "Successfully created maze."
      redirect_to new_maze_node_url(@maze)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @maze = current_user.mazes.find(params[:id])
    @nodes = @maze.nodes.all
  end
  
  def update
    @maze = current_user.mazes.find(params[:id])
    if @maze.update_attributes(params[:maze])
      flash[:notice] = "Successfully updated maze."
      redirect_to @maze
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @maze = current_user.mazes.find(params[:id])
    @maze.destroy
    flash[:notice] = "Successfully destroyed maze."
    redirect_to mazes_url
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController 
  
  before_filter :login_required
  before_filter :get_maze

  def index
    @nodes = @maze.nodes.all
  end
  
  def show
    @node = @maze.nodes.find(params[:id])
    get_links
  end
  
  def new
    @node = @maze.nodes.new
  end
  
  def create
    @node = @maze.nodes.new(params[:node])
    if @node.save
      flash[:notice] = "Successfully created node."
      redirect_to edit_maze_path(@maze)
    else
      render :action => 'new'
    end
  end
  
  def edit
    @node = @maze.nodes.find(params[:id])
    get_links
  end
  
  def update
    @node = @maze.nodes.find(params[:id])   
    if @node.update_attributes(params[:node])
      flash[:notice] = "Successfully updated node."
    else
      flash[:error] = "Node wasn't updated"
    end
    redirect_to edit_maze_path(@maze)
  end
  
  def destroy
    @node = @maze.nodes.find(params[:id])
    @node.destroy
    flash[:notice] = "Successfully destroyed node."
    redirect_to maze_nodes_url @maze 
  end
  
  protected
  
  
  def get_links
    @links = @node.links.all
  end  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default("/")
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to "/"
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/mazes_helper.rb
module MazesHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for [@maze,@node,@link] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.label :to_node_id %><br />
    <%= f.select :to_node_id, @nodes %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/links/edit.html.erb
<% title "Edit Link for #{@node.title}" %>

<%= render 'form' %>

app/views/links/new.html.erb
<% title "New Link for #{@node.title}" %>

<%= render 'form' %>

app/views/mazes/_form.html.erb
<%= form_for @maze do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p><%= f.submit %></p>
<% end %>

app/views/mazes/edit.html.erb
<% title "Edit Maze" %>

<%= render 'form' %>

<p>
  <strong>Nodes:</strong>
  <% @nodes.each do |node| %>
  	<p>
			<%= node.title %>
		  <%= link_to "Edit", edit_maze_node_path(@maze, node) %> |
		  <%= link_to "Destroy", [@maze, node], :confirm => 'Are you sure?', :method => :delete %>
		</p>
  <% end unless @nodes.nil? %>
  
</p>

<p>
  <%= link_to "Create Node", new_maze_node_path(@maze) %> |
  <%= link_to "Back", mazes_path %>
</p>

app/views/mazes/index.html.erb
<% title "Mazes" %>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% for maze in @mazes %>
    <tr>
      <td><%= maze.title %></td>
      <td><%= link_to "Play", maze %></td>
      <td><%= link_to "Edit", edit_maze_path(maze) %></td>
      <td><%= link_to "Destroy", maze, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Create Maze", new_maze_path %></p>

app/views/mazes/new.html.erb
<% title "New Maze" %>

<%= render 'form' %>

<p><%= link_to "Back to List", mazes_path %></p>

app/views/mazes/show.html.erb
<% title "Maze" %>

<p>
  <strong>Title:</strong>
  <%= @maze.title %>
</p>

<p>
  <%= link_to "Edit", edit_maze_path(@maze) %> |
  <%= link_to "Destroy", @maze, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", mazes_path %>
</p>

app/views/nodes/_form.html.erb
<%= form_for([@maze, @node]) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/nodes/_show_links.html.erb
  <strong>Links:</strong>
  <% @links.each do |link| %>
  	<p>
  	  <%= link_to link.text, maze_node_path(@maze, link.to_node_id) %>
  	  <%= link_to 'Edit', edit_maze_node_link_path(@maze, @node, link) if edit %>
  	</p> 
  <% end %>

app/views/nodes/edit.html.erb
<% title "Edit Node" %>

<%= render 'form' %>

<p>
<%= render :partial => 'show_links', :locals => {:edit  => true} %>
</p>

<p>
	<%= link_to "Add Link", new_maze_node_link_path(@maze, @node) %> |
  <%= link_to "Back", edit_maze_path(@maze) %>
</p>

app/views/nodes/index.html.erb
<% title "Nodes" %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  <% for node in @nodes %>
    <tr>
      <td><%= node.title %></td>
      <td><%= node.content %></td>
      <td><%= link_to "Show", [@maze, node] %></td>
      <td><%= link_to "Edit", edit_maze_node_path(@maze, node) %></td>
      <td><%= link_to "Destroy", [@maze, node], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Node", new_maze_node_path(@maze) %></p>

app/views/nodes/new.html.erb
<% title "New Node" %>

<%= render 'form' %>

<p><%= link_to "Back to List", maze_nodes_path(@maze) %></p>

app/views/nodes/show.html.erb
<% title "Node" %>

<p>
  <strong>Title:</strong>
  <%= @node.title %>
</p>
<p>
  <strong>Content:</strong>
  <%= @node.content %>
</p> 
<p>
<%= render :partial => 'show_links', :locals => {:edit  => nil} %>
</p>

<p><%= link_to 'Quit', mazes_path %></p>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>